import { User } from '../users/user.entity';
import { Column, CreateDateColumn, Entity, PrimaryGeneratedColumn, UpdateDateColumn, ManyToOne } from 'typeorm';

export enum AvailabilityTier {
  STANDARD = 'standard',
  HIGH = 'high',
}

export enum DatabaseType {
  STANDARD = 'standard',
  LIGHT = 'light',
}

@Entity('shops')
export class Shop {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ unique: true })
  name: string;

  @Column({ type: 'enum', enum: AvailabilityTier })
  availabilityTier: AvailabilityTier;

  @Column({ type: 'enum', enum: DatabaseType })
  databaseType: DatabaseType;

  @Column({ type: 'varchar', nullable: true })
  walletAddress: string | null;

  // Recorded once at creation time — walletAddress itself gets overwritten by
  // toView()'s status-poll side effect as soon as the operator resolves it,
  // for both auto-generated and user-supplied wallets, so it can't be used
  // later to infer whether generation was requested.
  @Column({ default: false })
  walletAutoGenerated: boolean;

  @Column({ type: 'timestamptz', nullable: true })
  credentialsViewedAt: Date | null;

  @Column()
  adminEmail: string;

  @ManyToOne(() => User)
  user: User;

  @Column()
  userId: string;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}
