import { ConflictException, ForbiddenException, GoneException, NotFoundException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { Test } from '@nestjs/testing';
import { getRepositoryToken } from '@nestjs/typeorm';
import { ShopResourceService } from '../kubernetes/shop-resource.service';
import { MetricsService } from '../observability/metrics.service';
import { AvailabilityTier, DatabaseType, Shop } from './shop.entity';
import { ShopService } from './shop.service';

const mockRepo = {
  findOneBy: jest.fn(),
  findBy: jest.fn(),
  save: jest.fn(),
  create: jest.fn(),
  remove: jest.fn(),
};

const mockK8s = {
  createShop: jest.fn().mockResolvedValue(undefined),
  patchShop: jest.fn().mockResolvedValue(undefined),
  deleteShopNamespace: jest.fn().mockResolvedValue(undefined),
  waitForReady: jest.fn().mockResolvedValue(undefined),
  readAdminCredentials: jest.fn().mockResolvedValue({ email: 'a@b.c', password: 'pw' }),
  readShopStatus: jest.fn().mockResolvedValue({ walletAddress: undefined }),
  readWalletCredentials: jest.fn().mockResolvedValue({ address: '0xgen', privateKey: '0xpriv' }),
  readShopPhase: jest.fn().mockResolvedValue({ phase: 'Progressing', reason: null }),
};

const mockMetrics = {
  shopCreated: { inc: jest.fn() },
  shopDeleted: { inc: jest.fn() },
  shopFetched: { inc: jest.fn() },
  userCreated: { inc: jest.fn() },
};

const mockConfig = {
  getOrThrow: jest.fn((key: string) =>
    ({ SHOP_API_IMAGE: 'ghcr.io/shopp-ops/shop-api:1', SHOP_WEB_IMAGE: 'ghcr.io/shopp-ops/shop-web:1' })[key],
  ),
  get: jest.fn(() => 'local'),
};

describe('ShopService', () => {
  let service: ShopService;

  beforeEach(async () => {
    jest.clearAllMocks();
    mockK8s.createShop.mockResolvedValue(undefined);
    mockK8s.patchShop.mockResolvedValue(undefined);
    mockK8s.deleteShopNamespace.mockResolvedValue(undefined);
    mockK8s.waitForReady.mockResolvedValue(undefined);
    mockK8s.readAdminCredentials.mockResolvedValue({ email: 'a@b.c', password: 'pw' });
    mockK8s.readShopStatus.mockResolvedValue({ walletAddress: undefined });
    mockK8s.readWalletCredentials.mockResolvedValue({ address: '0xgen', privateKey: '0xpriv' });
    mockK8s.readShopPhase.mockResolvedValue({ phase: 'Progressing', reason: null });
    const module = await Test.createTestingModule({
      providers: [
        ShopService,
        { provide: getRepositoryToken(Shop), useValue: mockRepo },
        { provide: MetricsService, useValue: mockMetrics },
        { provide: ShopResourceService, useValue: mockK8s },
        { provide: ConfigService, useValue: mockConfig },
      ],
    }).compile();
    service = module.get(ShopService);
  });

  describe('findByIdForUser', () => {
    it('throws NotFoundException when shop does not exist', async () => {
      mockRepo.findOneBy.mockResolvedValue(null);
      await expect(service.findByIdForUser('shop-1', 'user-1')).rejects.toThrow(NotFoundException);
    });

    it('throws ForbiddenException when shop belongs to another user', async () => {
      mockRepo.findOneBy.mockResolvedValue({ id: 'shop-1', userId: 'user-2' });
      await expect(service.findByIdForUser('shop-1', 'user-1')).rejects.toThrow(ForbiddenException);
    });

    it('returns shop when userId matches', async () => {
      const shop = { id: 'shop-1', userId: 'user-1' };
      mockRepo.findOneBy.mockResolvedValue(shop);
      await expect(service.findByIdForUser('shop-1', 'user-1')).resolves.toEqual(shop);
    });
  });

  describe('create', () => {
    const dto = {
      name: 'my-shop',
      adminEmail: 'admin@shop.local',
      availabilityTier: AvailabilityTier.STANDARD,
      walletAddress: '0x123',
      databaseType: DatabaseType.STANDARD,
    };
    const saved = { id: '7c9e6679-7425-40de-944b-e07fc1f90ae7', userId: 'user-1', ...dto };

    beforeEach(() => {
      mockRepo.create.mockReturnValue({ ...dto, userId: 'user-1' });
      mockRepo.save.mockResolvedValue(saved);
    });

    it('persists then creates the Shop CR', async () => {
      const result = await service.create('user-1', dto);
      expect(mockRepo.create).toHaveBeenCalledWith({ ...dto, userId: 'user-1', walletAutoGenerated: false });
      expect(mockK8s.createShop).toHaveBeenCalledWith(
        expect.objectContaining({ id: saved.id, name: 'my-shop', availability: 'standard', database: 'standard' }),
      );
      expect(result.shop).toEqual(saved);
    });

    it('marks walletAutoGenerated when no walletAddress is supplied', async () => {
      const { walletAddress: _omit, ...dtoWithoutWallet } = dto;
      await service.create('user-1', dtoWithoutWallet as typeof dto);
      expect(mockRepo.create).toHaveBeenCalledWith(
        expect.objectContaining({ walletAutoGenerated: true }),
      );
    });

    it('rolls back the DB row and rethrows when CR creation fails', async () => {
      mockK8s.createShop.mockRejectedValue(new Error('k8s down'));
      await expect(service.create('user-1', dto)).rejects.toThrow('k8s down');
      expect(mockRepo.remove).toHaveBeenCalledWith(saved);
    });

    it('create returns immediately after CR create without waiting for readiness', async () => {
      const result = await service.create('user-1', dto);
      expect(mockK8s.createShop).toHaveBeenCalledTimes(1);
      expect(mockK8s.waitForReady).not.toHaveBeenCalled();
      expect(result).toEqual({ shop: expect.objectContaining({ name: dto.name }) });
    });
  });

  describe('update', () => {
    const shop = {
      id: '7c9e6679-7425-40de-944b-e07fc1f90ae7',
      userId: 'user-1',
      name: 'my-shop',
      availabilityTier: AvailabilityTier.STANDARD,
    };

    it('throws ForbiddenException when updating a shop owned by another user', async () => {
      mockRepo.findOneBy.mockResolvedValue({ ...shop, userId: 'user-2' });
      await expect(
        service.update('shop-1', 'user-1', { availabilityTier: AvailabilityTier.HIGH }),
      ).rejects.toThrow(ForbiddenException);
      expect(mockK8s.patchShop).not.toHaveBeenCalled();
    });

    it('throws NotFoundException when shop does not exist', async () => {
      mockRepo.findOneBy.mockResolvedValue(null);
      await expect(service.update('shop-1', 'user-1', {})).rejects.toThrow(NotFoundException);
    });

    it('saves then patches the CR spec', async () => {
      mockRepo.findOneBy.mockResolvedValue(shop);
      mockRepo.save.mockResolvedValue({ ...shop, availabilityTier: AvailabilityTier.HIGH });

      await service.update(shop.id, 'user-1', { availabilityTier: AvailabilityTier.HIGH });

      expect(mockRepo.save).toHaveBeenCalledWith({ ...shop, availabilityTier: AvailabilityTier.HIGH });
      expect(mockK8s.patchShop).toHaveBeenCalledWith('shop-my-shop-7c9e6679', 'my-shop-7c9e6679', {
        availability: 'high',
      });
    });

    it('does not patch when the dto maps to an empty spec', async () => {
      mockRepo.findOneBy.mockResolvedValue(shop);
      mockRepo.save.mockResolvedValue(shop);
      await service.update(shop.id, 'user-1', {});
      expect(mockK8s.patchShop).not.toHaveBeenCalled();
    });

    it('rolls back to the original row and rethrows when the patch fails', async () => {
      mockRepo.findOneBy.mockResolvedValue(shop);
      mockRepo.save.mockResolvedValue({ ...shop, availabilityTier: AvailabilityTier.HIGH });
      mockK8s.patchShop.mockRejectedValue(new Error('patch failed'));

      await expect(
        service.update(shop.id, 'user-1', { availabilityTier: AvailabilityTier.HIGH }),
      ).rejects.toThrow('patch failed');
      expect(mockRepo.save).toHaveBeenLastCalledWith({ ...shop });
    });
  });

  describe('remove', () => {
    const shop = {
      id: '7c9e6679-7425-40de-944b-e07fc1f90ae7',
      userId: 'user-1',
      name: 'my-shop',
    };

    it('throws NotFoundException when shop does not exist', async () => {
      mockRepo.findOneBy.mockResolvedValue(null);
      await expect(service.remove('shop-1', 'user-1')).rejects.toThrow(NotFoundException);
    });

    it('throws ForbiddenException when removing a shop owned by another user', async () => {
      mockRepo.findOneBy.mockResolvedValue({ ...shop, userId: 'user-2' });
      await expect(service.remove('shop-1', 'user-1')).rejects.toThrow(ForbiddenException);
      expect(mockK8s.deleteShopNamespace).not.toHaveBeenCalled();
    });

    it('removes the row then deletes the namespace', async () => {
      mockRepo.findOneBy.mockResolvedValue(shop);
      mockRepo.remove.mockResolvedValue(undefined);

      await service.remove(shop.id, 'user-1');

      expect(mockRepo.remove).toHaveBeenCalledWith(shop);
      expect(mockK8s.deleteShopNamespace).toHaveBeenCalledWith('shop-my-shop-7c9e6679');
    });

    it('swallows a NotFoundException from the namespace delete', async () => {
      mockRepo.findOneBy.mockResolvedValue(shop);
      mockK8s.deleteShopNamespace.mockRejectedValue(new NotFoundException());
      await expect(service.remove(shop.id, 'user-1')).resolves.toBeUndefined();
      expect(mockRepo.save).not.toHaveBeenCalled();
    });

    it('rolls back by re-inserting the row and rethrows on other failures', async () => {
      mockRepo.findOneBy.mockResolvedValue(shop);
      mockK8s.deleteShopNamespace.mockRejectedValue(new Error('delete failed'));
      await expect(service.remove(shop.id, 'user-1')).rejects.toThrow('delete failed');
      expect(mockRepo.save).toHaveBeenCalledWith({ ...shop });
    });
  });

  describe('findAllByUser', () => {
    const shopRow = {
      id: '7c9e6679-7425-40de-944b-e07fc1f90ae7',
      userId: 'user-1',
      name: 'my-shop',
      adminEmail: 'admin@shop.local',
      availabilityTier: AvailabilityTier.STANDARD,
      databaseType: DatabaseType.STANDARD,
      walletAddress: '0x123',
      credentialsViewedAt: null as Date | null,
    };

    it('attaches live phase and reason from the CR', async () => {
      mockRepo.findBy.mockResolvedValue([shopRow]);
      jest.spyOn(mockK8s, 'readShopPhase').mockResolvedValue({ phase: 'Failed', reason: 'api: ImagePullBackOff' });
      const [view] = await service.findAllByUser(shopRow.userId);
      expect(view.phase).toBe('Failed');
      expect(view.statusReason).toBe('api: ImagePullBackOff');
    });

    it('falls back to Unknown phase and null reason when readShopPhase throws', async () => {
      mockRepo.findBy.mockResolvedValue([shopRow]);
      jest.spyOn(mockK8s, 'readShopPhase').mockRejectedValue(new Error('k8s down'));
      const [view] = await service.findAllByUser(shopRow.userId);
      expect(view.phase).toBe('Unknown');
      expect(view.statusReason).toBeNull();
    });

    it('backfills the operator-generated wallet address from the CR status', async () => {
      const autoGenRow = { ...shopRow, walletAddress: null as string | null };
      mockRepo.findBy.mockResolvedValue([autoGenRow]);
      jest.spyOn(mockK8s, 'readShopStatus').mockResolvedValue({ walletAddress: '0xGENERATED' });
      const [view] = await service.findAllByUser(autoGenRow.userId);
      expect(view.walletAddress).toBe('0xGENERATED');
      expect(mockRepo.save).toHaveBeenCalledWith(expect.objectContaining({ walletAddress: '0xGENERATED' }));
    });
  });

  describe('getCredentials', () => {
    const shopForCreds = {
      id: '7c9e6679-7425-40de-944b-e07fc1f90ae7',
      userId: 'user-1',
      name: 'my-shop',
      adminEmail: 'admin@shop.local',
      availabilityTier: AvailabilityTier.STANDARD,
      databaseType: DatabaseType.STANDARD,
      walletAddress: '0x123',
      credentialsViewedAt: null as Date | null,
    };

    beforeEach(() => {
      shopForCreds.credentialsViewedAt = null;
      mockRepo.findOneBy.mockResolvedValue(shopForCreds);
      mockRepo.save.mockResolvedValue(shopForCreds);
    });

    it('returns 409 when the shop is not Ready', async () => {
      jest.spyOn(mockK8s, 'readShopPhase').mockResolvedValue({ phase: 'Progressing', reason: null });
      await expect(service.getCredentials(shopForCreds.id, shopForCreds.userId)).rejects.toBeInstanceOf(ConflictException);
    });

    it('returns creds once, then 410 Gone on the second call', async () => {
      jest.spyOn(mockK8s, 'readShopPhase').mockResolvedValue({ phase: 'Ready', reason: null });
      jest.spyOn(mockK8s, 'readAdminCredentials').mockResolvedValue({ email: 'a@b.c', password: 'pw' });
      const first = await service.getCredentials(shopForCreds.id, shopForCreds.userId);
      expect(first.adminCredentials?.password).toBe('pw');
      await expect(service.getCredentials(shopForCreds.id, shopForCreds.userId)).rejects.toBeInstanceOf(GoneException);
    });

    it('returns wallet credentials for an auto-generated wallet even after a status poll already filled in walletAddress', async () => {
      // Regression: a prior toView() call (e.g. the user watching the shop list
      // while it provisions) persists shop.walletAddress as soon as the operator
      // resolves it — for both auto-generated and user-supplied wallets. Deriving
      // "was this auto-generated?" from `!shop.walletAddress` at reveal time would
      // then always see it as already-set and skip readWalletCredentials.
      const autoGenShop = { ...shopForCreds, walletAddress: '0xALREADY_POLLED', walletAutoGenerated: true };
      mockRepo.findOneBy.mockResolvedValue(autoGenShop);
      jest.spyOn(mockK8s, 'readShopPhase').mockResolvedValue({ phase: 'Ready', reason: null });
      jest.spyOn(mockK8s, 'readShopStatus').mockResolvedValue({ walletAddress: '0xALREADY_POLLED' });
      jest.spyOn(mockK8s, 'readWalletCredentials').mockResolvedValue({ address: '0xALREADY_POLLED', privateKey: '0xpriv' });

      const result = await service.getCredentials(autoGenShop.id, autoGenShop.userId);

      expect(mockK8s.readWalletCredentials).toHaveBeenCalled();
      expect(result.walletCredentials).toEqual({ address: '0xALREADY_POLLED', privateKey: '0xpriv' });
    });

    it('does not return wallet credentials for a user-supplied wallet', async () => {
      const userWalletShop = { ...shopForCreds, walletAddress: '0xUSER_SUPPLIED', walletAutoGenerated: false };
      mockRepo.findOneBy.mockResolvedValue(userWalletShop);
      jest.spyOn(mockK8s, 'readShopPhase').mockResolvedValue({ phase: 'Ready', reason: null });
      jest.spyOn(mockK8s, 'readShopStatus').mockResolvedValue({ walletAddress: '0xUSER_SUPPLIED' });

      const result = await service.getCredentials(userWalletShop.id, userWalletShop.userId);

      expect(mockK8s.readWalletCredentials).not.toHaveBeenCalled();
      expect(result.walletCredentials).toBeNull();
    });
  });
});
